services:

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    restart: always
    env_file:
      - ./mariadb/.env.mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - $HOME/data/db:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=$(cat /run/secrets/db_root_password)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    build:
      context: ./bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
    - $HOME/data/redis:/data

  adminer:
    build:
      context: ./bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    environment: {}
    ports:
      - "8081:8080"
    networks:
      - inception

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    restart: always
    env_file:
      - ./wordpress/.env.wordpress
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - $HOME/data/wp/html:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "php-fpm81", "-t"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    environment:
      - NGINX_USER=${USER}
      - NGINX_HOST=${USER}.42.fr
    volumes:
      - $HOME/data/wp/html:/var/www/html:ro
    networks:
      - inception
    ports:
      - "443:443"
    extra_hosts:
      - "${USER}.42.fr:127.0.0.1"
    healthcheck:
      test: curl -k -f https://localhost/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  
  vsftpd:
    build:
      context: ./bonus/vsftpd
    container_name: vsftpd
    restart: always
    depends_on:
      - wordpress
    secrets:
      - ftp_password
    volumes:
      - $HOME/data/wp/html:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "20:20"
      - "30000-30009:30000-30009"
  
  grafana:
    build:
      context: ./bonus/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - $HOME/data/grafana:/var/lib/grafana
    secrets:
      - db_password
    networks:
      - inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt

networks:
  inception:
    driver: bridge
