apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    url: mariadb:3306
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${MARIADB_PASSWORD}
    isDefault: true
    editable: true
